# Dockerfile for Python Application
FROM python:3.11-slim

ARG EQTY_REPOSITORY
ARG EQTY_TRUSTED_HOST_DOMAIN
ARG EQTY_TRUSTED_HOST_USERNAME
ARG EQTY_TRUSTED_HOST_PASSWORD
ARG ENV

WORKDIR /living-content-api

# Install required packages
RUN apt-get update && apt-get install -y curl ca-certificates

# Set up a virtual environment and install dependencies
COPY requirements/requirements.txt /living-content-api/requirements/requirements.txt

RUN python -m venv venv \
  && . venv/bin/activate \
  && pip install --no-cache-dir -r /living-content-api/requirements/requirements.txt \
  --extra-index-url http://$EQTY_TRUSTED_HOST_USERNAME:$EQTY_TRUSTED_HOST_PASSWORD@$EQTY_TRUSTED_HOST_DOMAIN/simple/ \
  --trusted-host $EQTY_TRUSTED_HOST_DOMAIN \
  && deactivate

# Copy the application source code
COPY app/ /living-content-api/app
COPY main.py /living-content-api/main.py

# Expose port 8000
EXPOSE 8000

# Copy the entrypoint script
COPY scripts/api/api-entrypoint.sh /living-content-api/api-entrypoint.sh

# CHMOD the entrypoint script
RUN chmod +x /living-content-api/api-entrypoint.sh

ENTRYPOINT ["/living-content-api/api-entrypoint.sh"]