# ----------------------------------------------------------------
# Clients
# ----------------------------------------------------------------
clients:
  # Configuration for OpenAI client
  openai:
    max_tokens: 8192
    models:
      default: gpt-4o-2024-08-06
      function_selection: gpt-4o
