# ----------------------------------------------------------------
# Clients
# ----------------------------------------------------------------
clients:
  # Configuration for OpenAI client
  openai:
    max_tokens: 8192
    model: gpt-4o-2024-08-06
