# ----------------------------------------------------------------
# Ingress rules
# ----------------------------------------------------------------
ingress:
  allowed_origins:
    - https://localhost
    - https://localhost:8080
  excluded_paths:
    - /access-token/user-creation-token/create
    - /user/create
    - /access-token/auth/regenerate
    - /image-generator/apiframe/response
    - /docs
    - /openapi.json
    - /redoc
    - /healthz
    - /favicon.ico
  api_host_url: https://localhost
  api_port: 8000
  api_ssl_pem: ./.ssl/api/api.pem
  api_ssl_key: ./.ssl/api/api.key
  api_ssl_crt: ./.ssl/api/api.crt
  shared_ssl_pem: ./.ssl/shared/shared.pem
  shared_ssl_key: ./.ssl/shared/shared.key
  shared_ssl_crt: ./.ssl/shared/shared.crt
  ssl_ca_crt: ./.ssl/ca/ca.crt
