# ----------------------------------------------------------------
# Project definitions
# ----------------------------------------------------------------
project:
  namespace: living-content
  name: my-living-content-project
